# Server settings  
server:  
    port: 8080

spring:
  datasource:
     url: jdbc:mysql://106.15.120.125:21906/artemis?useUnicode=true&characterEncoding=utf8
     username: artemis
     password: 123456Ms3
     driver-class-name: com.mysql.jdbc.Driver        
        
# MyBatis  
mybatis:  
    typeAliasesPackage: indi.test.ureport.entity
    mapperLocations: classpath:/indi/**/mapper/*.xml
  
  
# 日志配置
logging:
  level:
    org.apache.ibatis: DEBUG
    
# ureport Mysql 存储
ureport.mysql.provider:
  prefix: test-
  disabled: false

# FTP 配置
ftp:
 factory:
#   不启用ftp
  enable: false
  hostname: 192.168.56.1
  port: 21
  username: Administrator
  password: Liqiaolin
  client-timeout: 10000
  encoding: utf8
#  retry-times: 
#  passive-mode: 
#  file-type: 
#  rename-uploaded: true
#  enable: true

# ureport FTP 存储
ureport:
  ftp:
    provider:
      prefix: ftp-
      disabled: false
      basePath: ureport_file\
 
